main: org.ctp.coldstorage.ColdStorage
version: 1.0.2
name: ColdStorage
api-version: 1.13
commands:
    csopen:
        description: Opens the cold storage
    csreload:
        description: Reload the cold storage configs
permissions:
    coldstorage.reload:
        description: Allows player to reload the configs
        default: op